<template>
  <tier-table v-model="search" :headers="headers" :items="tiers" :pagination="pagination" title="Epic 7 Tier List (PvE)" />
</template>

<script>
import TierTable from '~/components/TierTable.vue'

export default {
  components: {
    TierTable
  },

  data() {
    return {
      search: '',
      pagination: {
        descending: true,
        sortBy: 'star'
      },
      headers: [
        {
          text: '',
          align: 'left',
          sortable: false,
          value: 'img',
          class: 'pa-1'
        },
        { text: 'Name', value: 'name', class: 'pa-1' },
        { text: '★', value: 'star', class: 'pa-1' },
        { text: 'Element', value: 'element', class: 'pa-1' },
        { text: 'Class', value: 'class', class: 'pa-1' },
        { text: 'Hunt', value: 'hunt', class: 'pa-1' },
        { text: 'Abyss', value: 'abyss', class: 'pa-1' },
        { text: 'Raid', value: 'raid', class: 'pa-1' },
        { text: 'PvE Average', value: 'pve_average', class: 'pa-1' },
        { text: 'Recommended Set', value: 'recommended_set', class: 'pa-1' },
        { text: 'Neck', value: 'neck', class: 'pa-1' },
        { text: 'Suggested Roles', value: 'suggested_roles', class: 'pa-1' },
        { text: 'Recommended Artifact', value: 'recommended_artifact', class: 'pa-1' },
        { text: 'Alternative Artifact', value: 'alternate_artifact', class: 'pa-1' },
        { text: 'Alternative Artifact', value: 'alternate_artifact2', class: 'pa-1' },
        { text: 'Note', value: 'note', class: 'pa-1 cl-tier-note' }
      ],

      tiers: [
        { img: 'https://i.imgur.com/UVNF52L.png',
          name: 'Judge Kise',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6,
          abyss: 7.5,
          raid: 8.5,
          pve_average: 7.333333333333333,
          recommended_set: 'speed/crit\nspeed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Skill Delay\nAoE DPS\nDef Breaker\n',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/3vxEQrz.png',
          alternate_artifact2: '',
          note: 'More of a PvP unit, Skill Delay is a useful at many bosses and AoE damage is desirable.' },
        { img: 'https://i.imgur.com/iiLnGBp.png',
          name: 'Maid Chloe',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8,
          abyss: 8.5,
          raid: 8,
          pve_average: 8.166666666666666,
          recommended_set: 'speed/HP',
          neck: 'HP',
          suggested_roles: 'Healer\nBuffer',
          recommended_artifact: 'https://i.imgur.com/Oe2Xy9O.png',
          alternate_artifact: 'https://i.imgur.com/4jLh7K3.png',
          alternate_artifact2: 'https://i.imgur.com/sEynPik.png',
          note: undefined },
        { img: 'https://i.imgur.com/6IoiYyO.png',
          name: 'Ruele of Light',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8,
          abyss: 7.5,
          raid: 8,
          pve_average: 7.833333333333333,
          recommended_set: 'speed/HP\nALL HP',
          neck: 'HP',
          suggested_roles: 'Healer\nCleanse\nTank',
          recommended_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact: 'https://i.imgur.com/4jLh7K3.png',
          alternate_artifact2: 'https://i.imgur.com/sEynPik.png',
          note:
          'Mostly used as a best PvP defender, her single target heal and revive is pretty viable at certain situation like Wyvern 11.' },
        { img: 'https://i.imgur.com/RGhfrfF.png',
          name: 'Sage Baal & Sezan (WIP)',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8,
          abyss: 7,
          raid: 7,
          pve_average: 7.333333333333333,
          recommended_set: 'speed/hit',
          neck: '',
          suggested_roles: 'Dispel\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: undefined,
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/NIWlhHw.png',
          name: 'Silver Blade Aramintha\n',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 9,
          abyss: 9,
          raid: 9,
          pve_average: 9,
          recommended_set: 'speed/hit\nrage/crit',
          neck: 'CritR\nATK',
          suggested_roles: 'AoE DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/OodTyhI.png',
          name: 'Specimen Sez',
          star: 5,
          element: 'Light',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 5,
          abyss: 5.5,
          raid: 5,
          pve_average: 5.166666666666667,
          recommended_set: 'speed/crit\ncritD/crit ',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: '',
          note: 'PvP unit.' },
        { img: 'https://i.imgur.com/8Kvg5XO.png',
          name: 'Chloe',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 9,
          abyss: 8,
          raid: 7.5,
          pve_average: 8.166666666666666,
          recommended_set: 'critD/crit\nspeed/crit ',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/jlfXLQF.png',
          alternate_artifact: 'https://i.imgur.com/NA8VplW.png',
          alternate_artifact2: '',
          note:
          'One of convenient dps choices in Wyvern hunt, great against any boss with a fast attacker (flat 2% HP per attack under Magic Nail), her S3 multi is also super high (~700%) with Magic Nail and SB. ' },
        { img: 'https://i.imgur.com/xbLwZOj.png',
          name: 'Diene',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 10,
          abyss: 10,
          raid: 10,
          pve_average: 10,
          recommended_set: 'speed/DEF speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Buffer\nCleanse\nHealer',
          recommended_artifact: 'https://i.imgur.com/eG33ZVm.png',
          alternate_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact2: 'https://i.imgur.com/4jLh7K3.png',
          note:
          'Top buffer in game. Besides ATK buff/crit resist, she also has fast aoe cleanse/strong barrier. Soul spammer and decent healing with Rod. She has better Morale than Tama but lacks burst dmg and solid healing in comparison.' },
        {
          img: 'https://i.imgur.com/KBfJARg.png,1)")',
          name: 'Dizzy (WIP)',
          star: 5,
          element: 'Ice',
          class: '',
          hunt: 8,
          abyss: 9.5,
          raid: 9.5,
          pve_average: 9,
          recommended_set: 'speed/hit',
          neck: '',
          suggested_roles: 'Debuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Great damage mitigation through her debuffs.' },
        { img: 'https://i.imgur.com/y6xHrdv.png',
          name: 'Kise',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 9.5,
          abyss: 9,
          raid: 9,
          pve_average: 9.166666666666666,
          recommended_set: 'speed/crit critD/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nSkill Delay',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/PAlSNOv.png',
          note:
          'Her skill delay is incredibly useful in all modes since it can be used against bosses. Juicy S1 against Wyvern\'s shield and great S3 multi for burst.' },
        { img: 'https://i.imgur.com/U6WFIas.png',
          name: 'Krau',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 9,
          abyss: 8,
          raid: 8,
          pve_average: 8.333333333333334,
          recommended_set: 'ALL HP HP/DEF',
          neck: 'HP',
          suggested_roles: 'Tank\nBuffer\nST DPS',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: 'https://i.imgur.com/eRI1g9W.png',
          note: 'Solid defensive tank.' },
        { img: 'https://i.imgur.com/U7qdtYf.png',
          name: 'Luna',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 10,
          abyss: 9.5,
          raid: 9,
          pve_average: 9.5,
          recommended_set: 'speed/crit\ncritD/crit ',
          neck: 'critD',
          suggested_roles: 'ST DPS\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/3KKoV92.png',
          alternate_artifact2: '',
          note:
          'She\'s a Lorina level all-round dpser with avg 1.4 multi on s1 and 1.3 on passive. Top Wyvern killer, easily 3man w10/11. Her gearing is convenient with 30% crit rate up. Speed is welcomed, def break coverage at roughly 2 of 4.3 turns.' },
        { img: 'https://i.imgur.com/3LADco2.png',
          name: 'Sez',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 8.5,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.333333333333334,
          recommended_set: 'ATK/crit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact2: 'https://i.imgur.com/qgG8TFl.png',
          note: 'Great burst damage, good farmer and decent at Wyvern.' },
        { img: 'https://i.imgur.com/jmglPw9.png',
          name: 'Sigret',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 8,
          raid: 8,
          pve_average: 8.166666666666666,
          recommended_set: 'ATK/crit\nlifesteal/crit',
          neck: 'critR\nATK',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/jlfXLQF.png',
          alternate_artifact2: 'https://i.imgur.com/NA8VplW.png',
          note: 'Solid Ice dps based on debuffs.' },
        { img: 'https://i.imgur.com/Af0eYk8.png',
          name: 'Tywin',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 9.5,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.666666666666666,
          recommended_set: 'speed/HP',
          neck: 'HP',
          suggested_roles: 'Buffer\nDef Breaker\nTank',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: 'https://i.imgur.com/eRI1g9W.png',
          note:
          'He gets a hidden buff to target the highest atk. Can be a great buffer of those who want to save 50% crit chance for more ATK/critD, also an AoE def breaker and CR pusher. His S1 dispel is useful at sometime.' },
        { img: 'https://i.imgur.com/PNxIwTh.png',
          name: 'Yuna',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 8,
          abyss: 6,
          raid: 7.5,
          pve_average: 7.166666666666667,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'Buffer\nAoE DPS',
          recommended_artifact: 'https://i.imgur.com/EqJsrv8.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/vcX97Fa.png',
          note:
          'Gains .5 - 1 rating when paired with C. Dominiel. She deals AoE on every attack and has useful Attack/Speed buff, could be used in Hunt and as a farmer, but overshadowd by many other choices due to coverage/dmg multi.' },
        { img: 'https://i.imgur.com/gZJk2fb.png',
          name: 'Zeno',
          star: 5,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 5,
          raid: 5,
          pve_average: 5.333333333333333,
          recommended_set: 'speed/HP     ATK/HP',
          neck: 'critR\nHP',
          suggested_roles: 'Debuffer\nDPS',
          recommended_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'The kit is more focused on PvP defense.' },
        { img: 'https://i.imgur.com/WxqjT2B.png", 1)',
          name: 'Aramintha',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 9.5,
          abyss: 7.5,
          raid: 9,
          pve_average: 8.666666666666666,
          recommended_set: 'ATK/crit speed/crit',
          neck: 'critR\nATK',
          suggested_roles: 'Debuffer\nAoE DPS\nBuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/suDA1MA.png',
          name: 'Baal & Sezan',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8.5,
          abyss: 7.5,
          raid: 8,
          pve_average: 8,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer\nAoE DPS',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/Mvc1ufa.png',
          name: 'Cecilia',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 6,
          abyss: 7,
          raid: 7.5,
          pve_average: 6.833333333333333,
          recommended_set: '2HP/DEF speed/HP',
          neck: 'HP',
          suggested_roles: 'Def Breaker\nDebuffer\nTank',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note: undefined },
        { img: 'https://i.imgur.com/Hm8KQej.png',
          name: 'Cermia',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 10,
          abyss: 8.5,
          raid: 8.5,
          pve_average: 9,
          recommended_set: 'critD/crit   ATK/crit    speed/crit',
          neck: 'critD\ncritR',
          suggested_roles: 'ST DPS',
          recommended_artifact: 'https://i.imgur.com/Ht6yi2o.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/MNzXzsM.png',
          name: 'Charlotte',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 7.5,
          abyss: 7,
          raid: 8.5,
          pve_average: 7.666666666666667,
          recommended_set: 'speed/crit    lifesteal/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nAoE DPS',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/eRI1g9W.png',
          alternate_artifact2: '',
          note: 'Grea AoE kit, perform well in Raid.' },
        { img: 'https://i.imgur.com/tSnnDM0.png',
          name: 'Haste',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 10,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.833333333333334,
          recommended_set: 'speed/crit ATK/hit',
          neck: 'critR\nATK',
          suggested_roles: 'Debuffer\nDPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/LTUtTM7.png,1")',
          note:
          'Top utility dpser with high multi, reliable healing and best heal prohibiting. He can make Golem 10 and Wyvern 10 much easier. Also very helpful in any boss that needs to hinder the healing.' },
        { img: 'https://i.imgur.com/PN3NcXO.png',
          name: 'Kayron',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 7,
          abyss: 7.5,
          raid: 7.5,
          pve_average: 7.333333333333333,
          recommended_set: 'ATK/crit lifesteal/HP',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nSelf-Buff',
          recommended_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/vI1I5KU.png',
          note:
          'Immunity set can turn his S1 into AOE and refresh at every wave.\n' },
        { img: 'https://i.imgur.com/duYUKIr.png',
          name: 'Ken',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 10,
          abyss: 9,
          raid: 9,
          pve_average: 9.333333333333334,
          recommended_set: 'ATK/HP   lifesteal/HP',
          neck: 'critR\nATK',
          suggested_roles: 'Def Breaker\nST DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/EaeYc7N.png',
          note:
          'After the rework, 100% Def Break (ignore res) on S2 + 35% Def Break on S1 make him top Def Breaker. Vigor gives him extra 30% so his dmg is desirable. 100% Atk Decrease + high base HP (7323) are also a bonus.\n ' },
        { img: '',
          name: 'Lidica\n',
          star: 5,
          element: 'Fire',
          class: '',
          hunt: 9.5,
          abyss: 9.5,
          raid: 9.5,
          pve_average: 9.5,
          recommended_set: 'speed/crit\nspeed/unity',
          neck: 'critR\ncritD',
          suggested_roles: 'CR Delay\nST DPS\nDebuffer',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: 'https://i.imgur.com/6nIJ3yJ.png',
          note:
          '124 speed and strong CR delay can cheese Golem or any other bosses that isn\'t immune to it, if you have the slot to put her in. Would be much more useful when harder bosses come out.' },
        { img: 'https://i.imgur.com/ScmnxL7.png',
          name: 'Ravi',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 9.5,
          abyss: 9,
          raid: 9,
          pve_average: 9.166666666666666,
          recommended_set: 'critD/crit\nATK/crit\ncounter/HP',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/3KKoV92.png',
          alternate_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'With her 1.6X passive modifier, she\'s Lorina level dmg dealer who can vamp-tank well. She can be a solid threat in all modes and doesn\'t need high investment (S1+4 is fine). You\'d like to always turn off her S3 to keep 1.6X buff.' },
        { img: 'https://i.imgur.com/Ffp6f0n.png',
          name: 'Sol (WIP)',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 10,
          abyss: 9.5,
          raid: 9,
          pve_average: 9.5,
          recommended_set: 'speed/crit\ncounter/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS Debuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: undefined,
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/CPjGAiv.png',
          name: 'Tamarinne',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 10,
          abyss: 10,
          raid: 10,
          pve_average: 10,
          recommended_set: 'speed/HP\nspeed/unity',
          neck: 'HP',
          suggested_roles: 'Support\nHealer\nBuffer',
          recommended_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact: 'https://i.imgur.com/eG33ZVm.png',
          alternate_artifact2: 'https://i.imgur.com/sEynPik.png',
          note:
          'After the great buff, she\'s a Diene level supporter, with better burst/healing and atk buff coverage (4/5), as well as top CR boosting capability. She can also be used at the same time with Diene to be a dual atk machine. Tome for faster cycling.' },
        { img: 'https://i.imgur.com/NrOXiKl.png',
          name: 'Tenebria',
          star: 5,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8.5,
          abyss: 6,
          raid: 6,
          pve_average: 6.833333333333333,
          recommended_set: 'ATK/crit\ncritD/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer\nAoE DPS',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/lah7i0M.png',
          name: 'Baiken (WIP)',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 8.5,
          abyss: 7.5,
          raid: 8,
          pve_average: 8,
          recommended_set: 'speed/hit speed/crit',
          neck: 'critR critD ATK',
          suggested_roles: 'ST DPS Support Debuffer',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/r7vftKy.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/mRI3Tgy.png',
          name: 'Basar',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 6,
          raid: 5,
          pve_average: 5.666666666666667,
          recommended_set: 'speed/hit    ',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer\nAoE DPS',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact2: '',
          note:
          'Primarily is used to deal AoE damage and buff removal. As all 3 of his moves have the ability to inflict debuffs. it gives him an innate boost in damage. S3 AOE buff removal and prevention debuff, S2 is AOE blindness, S1 transfers debuffs' },
        { img: 'https://i.imgur.com/isiVvw5.png',
          name: 'Bellona',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 10,
          abyss: 10,
          raid: 9,
          pve_average: 9.666666666666666,
          recommended_set: 'speed/unity\ncritD/unity',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/vcX97Fa.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/gawOoKy.png',
          note:
          'Crit dmg and speed give her high HP% dmg, and great def break coverage. She is also a top Banshee killer and farmer (5 aoe in 7 turns, 3 with def break). Can cheese most Abyss levels, even off element, while Bloodstone can heal to full HP.' },
        { img: 'https://i.imgur.com/EPM6W0l.png',
          name: 'Charles',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 9.5,
          abyss: 7,
          raid: 7.5,
          pve_average: 8,
          recommended_set: 'critD/unity\ncounter/ crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nBuffer\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/eRI1g9W.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note:
          'Charles main role is that of a DPS. His other function is that of debuffer on his S2 allowing for boss and mob buff control. His S3 provides more offense for your team while making his DPS better. His best value comes out of a pairing with Elbris Ritual Sword. ' },
        { img: 'https://i.imgur.com/DXFgxwa.png',
          name: 'Destina',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8.5,
          abyss: 8.5,
          raid: 9.5,
          pve_average: 8.833333333333334,
          recommended_set: 'speed/HP     counter/HP',
          neck: 'HP',
          suggested_roles: 'Healer\nTank\nCleanse',
          recommended_artifact: 'https://i.imgur.com/4jLh7K3.png',
          alternate_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact2: '',
          note:
          'More of a Tank/Healer than a Cleanser due to long S3 CD. Solid healer with great S1/SB healing. speed would be appreciated, counter set is also an option. Can tank effectively due to high base HP/DEF.' },
        { img: 'https://i.imgur.com/uRlXbii.png',
          name: 'Iseria',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 9,
          abyss: 9.5,
          raid: 9.5,
          pve_average: 9.333333333333334,
          recommended_set: 'speed/crit    speed/unity',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nDispel\nST DPS',
          recommended_artifact: 'https://i.imgur.com/JgJaNeW.png',
          alternate_artifact: 'https://i.imgur.com/vcX97Fa.png',
          alternate_artifact2: '',
          note:
          'One of the best utility attackers. She has considerable dmg, dispelling buff, top def break coverage, rare \'unable to buff\', and rarest cd reset ability. She can fit in most squads and the skillset can make Abyss and Raid easier.\n' },
        { img: 'https://i.imgur.com/rNT5mRD.png',
          name: 'Ludwig',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 5,
          raid: 5,
          pve_average: 5.333333333333333,
          recommended_set: 'critD/crit    rage/crit ',
          neck: 'critD',
          suggested_roles: 'Dispel\nDPS',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'The kit is more focused on PvP offense.' },
        { img: 'https://i.imgur.com/pOcfmrG.png',
          name: 'Vildred',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 10,
          abyss: 7,
          raid: 7.5,
          pve_average: 8.166666666666666,
          recommended_set: 'speed/crit\nALL crit',
          neck: 'critR\ncritD',
          suggested_roles: 'AoE DPS\nSelf-Buff',
          recommended_artifact: 'https://i.imgur.com/vI1I5KU.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Top farmer and top Banshee killer .' },
        { img: 'https://i.imgur.com/XimEM1E.png',
          name: 'Violet',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 9,
          abyss: 8,
          raid: 8,
          pve_average: 8.333333333333334,
          recommended_set: 'lifesteal/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/CL5uGyT.png',
          alternate_artifact: 'https://i.imgur.com/a5R1cQA.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'Undisputable best frontliner for Banshee and menace against Ice units in PvP. Safe, albeit somewhat slow farming unit as well. Works best when manual since AI will use S3 without full focus, dramatically reducing its usefulness.' },
        { img: 'https://i.imgur.com/Ejh0bus.png',
          name: 'Yufine',
          star: 5,
          element: 'Earth',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8,
          abyss: 8,
          raid: 7.5,
          pve_average: 7.833333333333333,
          recommended_set: 'critD/crit    rage/crit ',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDef Breaker\nDispel',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/jlfXLQF.png',
          alternate_artifact2: 'https://i.imgur.com/NA8VplW.png',
          note: undefined },
        { img: 'https://i.imgur.com/hnHjKLm.png',
          name: 'Arbiter Vildred',
          star: 5,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 5.5,
          abyss: 6.5,
          raid: 6.5,
          pve_average: 6.166666666666667,
          recommended_set: 'speed/crit ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'AoE DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact2: '',
          note: 'Mostly a PvP unit, can be used as a farmer.' },
        { img: 'https://i.imgur.com/RriVZWY.png',
          name: 'Dark Corvus',
          star: 5,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 5,
          abyss: 6,
          raid: 5.5,
          pve_average: 5.5,
          recommended_set: 'ALL HP counter/HP',
          neck: 'HP',
          suggested_roles: 'ST DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/EaeYc7N.png',
          alternate_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact2: '',
          note: 'The kit is more focused on PvP defense.' },
        { img: 'https://i.imgur.com/4HQFL0P.png',
          name: 'Martial Artist          Ken',
          star: 5,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 9,
          raid: 9,
          pve_average: 8.833333333333334,
          recommended_set: 'lifesteal/crit\ncounter/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDef Breaker\nTank   ',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/W1k8VeY.png',
          name: 'Specter Tenebria',
          star: 5,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8.5,
          abyss: 9,
          raid: 8.5,
          pve_average: 8.666666666666666,
          recommended_set: 'speed/crit    ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'She\'s one of the fastest Golem 10/11 killer after invested, both in auto and manual, via high speed, spamming poison and being top multi.' },
        { img: 'https://i.imgur.com/X4Y1xhu.png',
          name: 'Blaze Dingo',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 9.5,
          abyss: 9,
          raid: 9,
          pve_average: 9.166666666666666,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nHealer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: undefined,
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/YzpKIyX.png',
          name: 'Crimson Armin',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 6,
          abyss: 8.5,
          raid: 8.5,
          pve_average: 7.666666666666667,
          recommended_set: 'speed/DEF',
          neck: 'DEF\nHP',
          suggested_roles: 'Tank\nImmunity',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: 'https://i.imgur.com/6kPDlaB.png',
          note: 'Solid defensive tank with team Immunity and Invi.' },
        { img: 'https://i.imgur.com/B3Xs3rA.png',
          name: 'Fighter Maya',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 7,
          abyss: 6.5,
          raid: 6.5,
          pve_average: 6.666666666666667,
          recommended_set: 'ALL DEF\nspeed/DEF',
          neck: 'DEF',
          suggested_roles: 'Tank\nST DPS',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/TiBmE8q.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: 'A bulky DPS with high mullti based on DEF.' },
        { img: 'https://i.imgur.com/m6UJGXx.png',
          name: 'General Purrgis',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 9,
          abyss: 6.5,
          raid: 6,
          pve_average: 7.166666666666667,
          recommended_set: '4HP/DEF\nspeed/hit ',
          neck: 'DEF\nHP',
          suggested_roles: 'CR Pusher\nTank',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'Mainly used in PvP due to his fantastic S3. Wyvern 11 enables him to be a great CR pusher (30% CR per wyvern turn) too.' },
        { img: 'https://i.imgur.com/gTkdGt8.png',
          name: 'Guider Aither',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8,
          abyss: 9,
          raid: 9,
          pve_average: 8.666666666666666,
          recommended_set: 'ATK/crit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nHealer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'A perfect fit for an all healer team since he provides great damage on top of consistent heals. Kal\'adra is best used when paired with other debuffers so he can maximize the heal of his s3.' },
        { img: 'https://i.imgur.com/zwDKGKK.png',
          name: 'Wanderer Silk',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 7.5,
          abyss: 9,
          raid: 9,
          pve_average: 8.5,
          recommended_set: 'speed/hit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'CR Delay\nST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/JgJaNeW.png',
          alternate_artifact2: '',
          note:
          'One of the best Joker spammers, works well against high HP bosses with her CR delay and debuffs.' },
        { img: 'https://i.imgur.com/2kKVJ4D.png',
          name: 'Watcher Schuri',
          star: 4,
          element: 'Light',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 5,
          abyss: 6,
          raid: 6,
          pve_average: 5.666666666666667,
          recommended_set: 'critD/crit',
          neck: 'critD',
          suggested_roles: 'ST DPS',
          recommended_artifact: 'https://i.imgur.com/3vxEQrz.png',
          alternate_artifact: 'https://i.imgur.com/jIFaJQV.png',
          alternate_artifact2: '',
          note: 'The kit is more focused on PvP offense.' },
        { img: 'https://i.imgur.com/mZBmtXi.png',
          name: 'Angelica',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 10,
          abyss: 10,
          raid: 10,
          pve_average: 10,
          recommended_set: 'speed/HP   ALL HP',
          neck: 'HP',
          suggested_roles: 'Healer\nImmunity\nTank',
          recommended_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact: 'https://i.imgur.com/8Ylzm5P.png',
          alternate_artifact2: '',
          note:
          'Top benefiter of Meta, argubly best healer in PvE. With her 100% coverage Immunity and reliable healing, she makes Abyss, Raid and Wyvern 11 much easier.' },
        { img: 'https://i.imgur.com/e3zoJxs.png',
          name: 'Clarissa',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 7.5,
          raid: 8,
          pve_average: 8,
          recommended_set: 'ATK/hit   ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: 'https://i.imgur.com/NA8VplW.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/sWuKL4P.png',
          name: 'Coli',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 7,
          abyss: 6,
          raid: 7,
          pve_average: 6.666666666666667,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/PAlSNOv.png',
          note: undefined },
        { img: 'https://i.imgur.com/3q8gS0N.png',
          name: 'Crozet',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 9,
          abyss: 6.5,
          raid: 5,
          pve_average: 6.833333333333333,
          recommended_set: 'ALL HP    2DEF/HP    ',
          neck: 'DEF',
          suggested_roles: 'Tank',
          recommended_artifact: 'https://i.imgur.com/TiBmE8q.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note: undefined },
        { img: 'https://i.imgur.com/5CRWS0C.png',
          name: 'Dominiel',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 5.5,
          abyss: 5.5,
          raid: 5.5,
          pve_average: 5.5,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/3RJCkrc.png',
          name: 'Karin',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 9.5,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.666666666666666,
          recommended_set: 'rage/crit    critD/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: '',
          note:
          'Loses 1 rating when missing essential artifact.  100% crit chance is needed. Great single target damage dealer who can chain several turns together and def break. Top Wyvern killer.' },
        { img: 'https://i.imgur.com/KFZylnU.png',
          name: 'Romann',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 5,
          abyss: 5,
          raid: 5,
          pve_average: 5,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'AoE DPS\nDispel',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Mostly used in PvP for dispelling.' },
        { img: 'https://i.imgur.com/oQp3AsT.png',
          name: 'Rose',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 8,
          abyss: 7,
          raid: 7.5,
          pve_average: 7.5,
          recommended_set: 'speed/DEF',
          neck: 'DEF',
          suggested_roles: 'Buffer\nCR Pusher\nTank',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note: undefined },
        { img: 'https://i.imgur.com/fyYwMXC.png',
          name: 'Zerato',
          star: 4,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 5.5,
          abyss: 5,
          raid: 5,
          pve_average: 5.166666666666667,
          recommended_set: 'rage/crit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/ZTQ5NQT.png',
          name: 'Achates',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 9,
          abyss: 9,
          raid: 9.5,
          pve_average: 9.166666666666666,
          recommended_set: 'speed/HP   ALL HP',
          neck: 'HP',
          suggested_roles: 'Healer\nCleanse\nTank',
          recommended_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact2: '',
          note:
          'Top cleanser. With a 3 turn cd and candle, she can cast cleansing with high frequency. Great Morale capability for Normal Raid.' },
        { img: 'https://i.imgur.com/80Q85Zs.png',
          name: 'Corvus',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 4.5,
          abyss: 6.5,
          raid: 5,
          pve_average: 5.333333333333333,
          recommended_set: 'ALL DEF\nspeed/DEF',
          neck: 'DEF\nHP',
          suggested_roles: 'DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/EaeYc7N.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'Another tanky fighter, but provides support more than damage. Scales with defense, but takes a while to get warmed up.' },
        { img: 'https://i.imgur.com/0s4ZvjT.png',
          name: 'Dingo',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 7,
          abyss: 6.5,
          raid: 7,
          pve_average: 6.833333333333333,
          recommended_set: 'speed/crit speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nCleanse\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/EaeYc7N.png',
          alternate_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/IlMvmk4.png',
          name: 'Maya',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 5,
          abyss: 6.5,
          raid: 5.5,
          pve_average: 5.666666666666667,
          recommended_set: 'speed/def',
          neck: 'DEF',
          suggested_roles: 'Buffer\nTank',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/eRI1g9W.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note:
          'A great stunner with taunt, def buff in a long cooldown S3. Stun is quite limited in PvE except some levels in Abyss.' },
        { img: 'https://i.imgur.com/QzsttQf.png',
          name: 'Mercedes',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 7,
          abyss: 4,
          raid: 4,
          pve_average: 5,
          recommended_set: 'ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'AoE DPS',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact2: 'https://i.imgur.com/jQjtCwy.png',
          note: 'A starter unit with meh multi, not recommended.' },
        { img: 'https://i.imgur.com/KD0gHjf.png',
          name: 'Schuri',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 8.5,
          abyss: 8.5,
          raid: 8.5,
          pve_average: 8.5,
          recommended_set: 'speed/unity',
          neck: 'critR',
          suggested_roles: 'CR Pusher\nDPS',
          recommended_artifact: 'https://i.imgur.com/vcX97Fa.png',
          alternate_artifact: 'The recommended artifact is essential for this character.',
          alternate_artifact2: '',
          note:
          'Top CR pusher in current meta, his kit can give around 40% acceleration per turn with a maxed Rosa. Also has decent dps. 100% crit chance is needed and top speed is appreciated.\n' },
        { img: 'https://i.imgur.com/UuIx2Ny.png',
          name: 'Serila',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8,
          abyss: 7,
          raid: 7.5,
          pve_average: 7.5,
          recommended_set: 'speed/crit     atk/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: '',
          note: 'Skills with nice multi and spamable s2 that heals herself.' },
        { img: 'https://i.imgur.com/IozLRJl.png',
          name: 'Surin',
          star: 4,
          element: 'Fire',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 8,
          abyss: 7.5,
          raid: 7.5,
          pve_average: 7.666666666666667,
          recommended_set: 'ATK/crit   speed/crit',
          neck: 'critR\nATK',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'She can easily stack 7+ levels of Bleed, a pretty good choice for Wyvern 10 and some bosses weak to debuff.' },
        { img: 'https://i.imgur.com/vx186YF.png',
          name: 'Armin',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 6.5,
          abyss: 7.5,
          raid: 7,
          pve_average: 7,
          recommended_set: 'speed/DEF\n2DEF/HP',
          neck: 'DEF',
          suggested_roles: 'Buffer\nDebuffer\nTank',
          recommended_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note: undefined },
        { img: 'https://i.imgur.com/eFJ2Oil.png',
          name: 'Cartuja',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6.5,
          abyss: 6,
          raid: 7.5,
          pve_average: 6.666666666666667,
          recommended_set: 'speed/HP',
          neck: 'critR\nHP',
          suggested_roles: 'Def Breaker\nDPS',
          recommended_artifact: 'https://i.imgur.com/EaeYc7N.png',
          alternate_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact2: '',
          note:
          'A decent supporter with def break on S1, his merit is that he can easily have high (45+) morale team.' },
        { img: 'https://i.imgur.com/CF3o9zf.png',
          name: 'Cidd',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 9.5,
          abyss: 8.5,
          raid: 7.5,
          pve_average: 8.5,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'Great kit with stable def break and double enhanced S1, can be used as a top general DPS, but Raid\'s meta (unable to buff, dispel, fire) hinders him there.' },
        { img: 'https://i.imgur.com/vsJosuc.png',
          name: 'Leo',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 6.5,
          abyss: 5.5,
          raid: 5.5,
          pve_average: 5.833333333333333,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nDPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/JgJaNeW.png',
          alternate_artifact: 'https://i.imgur.com/EqSBN8P.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/KH5Xm2R.png',
          name: 'Lots',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8.5,
          abyss: 8,
          raid: 8,
          pve_average: 8.166666666666666,
          recommended_set: 'speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Healer\nCR Pusher',
          recommended_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact: 'https://i.imgur.com/Oe2Xy9O.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/YjX2qIS.png',
          name: 'Purrgis',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6,
          abyss: 5.5,
          raid: 6,
          pve_average: 5.833333333333333,
          recommended_set: 'counter/HP\ncounter/DEF',
          neck: 'critR\ncritD',
          suggested_roles: 'AoE DPS\nTank',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/NA8VplW.png',
          note: undefined },
        { img: 'https://i.imgur.com/IIQhPSW.png',
          name: 'Rin',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 7.5,
          abyss: 7,
          raid: 8,
          pve_average: 7.5,
          recommended_set: 'speed/hit',
          neck: 'HP',
          suggested_roles: 'Healer\nBuffer',
          recommended_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/4i3ma1a.png',
          name: 'Silk',
          star: 4,
          element: 'Earth',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 8,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.166666666666666,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nBuffer\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/xX1BRyt.png',
          alternate_artifact2: 'https://i.imgur.com/VeN5nfe.png',
          note: '\n' },
        { img: 'https://i.imgur.com/UupabG5.png',
          name: 'Assassin Cartuja',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 9,
          raid: 9,
          pve_average: 8.833333333333334,
          recommended_set: 'lifesteal/crit   speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nSupport\nDPS/Tank',
          recommended_artifact: 'https://i.imgur.com/EaeYc7N.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'A general bruiser with def break, can tank well with gurantee Evasion on self and give a team-wide 15% Evasion buff. Has decent dps.' },
        { img: 'https://i.imgur.com/AtgDVqA.png',
          name: 'Assassin Cidd',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 7.5,
          abyss: 8,
          raid: 7,
          pve_average: 7.5,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'Mostly used in PvP as a top speed CC, the poison proc and S3 dmg can be decent.' },
        { img: 'https://i.imgur.com/PGC4VII.png',
          name: 'Assassin Coli',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 7,
          abyss: 8,
          raid: 7.5,
          pve_average: 7.5,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS',
          recommended_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/yjOmlWX.png',
          name: 'Auxiliary Lots',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 6,
          raid: 6.5,
          pve_average: 6.166666666666667,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nCR Pusher\nBuffer',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/1IAXhSi.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: 'The kit is more focused on PvP offense.' },
        { img: 'https://i.imgur.com/Dafvq4C.png',
          name: 'Blood Blade Karin',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 6.5,
          abyss: 7,
          raid: 8,
          pve_average: 7.166666666666667,
          recommended_set: 'lifesteal/crit critD/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS',
          recommended_artifact: 'https://i.imgur.com/vI1I5KU.png',
          alternate_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/sMWkXww.png',
          name: 'Celestial Mercedes',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8.5,
          abyss: 7,
          raid: 7.5,
          pve_average: 7.666666666666667,
          recommended_set: 'critD/crit',
          neck: 'critD',
          suggested_roles: 'AoE DPS',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: 'https://i.imgur.com/jQjtCwy.png',
          note:
          'S2 scales dmg with enemy hp makes her viable in hunts, s3 is a strong aoe that gives her readiness as well as a two turn attk buff, easily farmed formation bonus as well for party c.chance.' },
        { img: 'https://i.imgur.com/8HoQcAf.png',
          name: 'Challenger Dominiel',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 9,
          abyss: 9.5,
          raid: 10,
          pve_average: 9.5,
          recommended_set: 'rage/crit    critD/crit',
          neck: 'critD',
          suggested_roles: 'ST DPS\nCR Pusher',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/3KKoV92.png',
          alternate_artifact2: '',
          note:
          'Best burst dmg in the game, can skip Hell bosses\' phases easily. Mostly due to her S1 SB multi and S2, but also because her crit chance boost enables crit damage necklace, and no need for speed boot. Notice that S2 skillup has a low income.' },
        { img: 'https://i.imgur.com/3RUfjmo.png',
          name: 'Crescent Moon Rin (WIP)',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 8,
          abyss: 9,
          raid: 9.5,
          pve_average: 8.833333333333334,
          recommended_set: 'speed/hit',
          neck: 'critR',
          suggested_roles: 'Buffer Debuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/PAlSNOv.png',
          note: undefined },
        { img: 'https://i.imgur.com/HoMOpdq.png',
          name: 'Kitty Clarissa',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8,
          abyss: 8,
          raid: 8,
          pve_average: 8,
          recommended_set: 'speed/HP    ',
          neck: 'critR\ncritD',
          suggested_roles: 'Support\nCleanse',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact2: 'https://i.imgur.com/MMaS2yK.png',
          note:
          'Has a pretty good 3-turn CD heal ban to shine in Golem, beside that she\'s a dual-atker with 3/5 coverage. If you can pair her with strong S1er such as Ravi it would be profiable as almost 1.6X dmg .\n' },
        { img: 'https://i.imgur.com/N0dZAuT.png',
          name: 'Shadow Rose',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 8.5,
          abyss: 8,
          raid: 9,
          pve_average: 8.5,
          recommended_set: 'speed/hit',
          neck: 'DEF\nHP',
          suggested_roles: 'CR Pusher\nDef Breaker\nDispel',
          recommended_artifact: 'https://i.imgur.com/6kPDlaB.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: '',
          note:
          'Has best def break coverage and a huge CR swing with her S3. Her formation bonus gives dual chance as well. Ideal for most content, but arena and raid in particular.' },
        { img: 'https://i.imgur.com/wKMXx4z.png',
          name: 'Shooting Star Achates',
          star: 4,
          element: 'Dark',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 6,
          abyss: 7.5,
          raid: 7.5,
          pve_average: 7,
          recommended_set: 'speed/DEF\nspeed/HP',
          neck: 'HP',
          suggested_roles: 'Healer',
          recommended_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/D7q0Srs.png',
          name: 'Arowell',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 4,
          abyss: 4,
          raid: 4,
          pve_average: 4,
          recommended_set: 'speed/DEF\n',
          neck: 'DEF',
          suggested_roles: 'Tank',
          recommended_artifact: 'https://i.imgur.com/eRI1g9W.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note: undefined },
        { img: 'https://i.imgur.com/r5KEpHG.png',
          name: 'Captain Rikoris',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 9,
          abyss: 7.5,
          raid: 7.5,
          pve_average: 8,
          recommended_set: 'speed/hit\nspeed/HP',
          neck: 'HP',
          suggested_roles: 'Def Breaker\nDispel\nBuffer',
          recommended_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/3vxEQrz.png',
          note:
          'THE NERF hurt him so much, no continous healing and cooldown+1 make him barely worthy for a position in good team, while things left are S1 35% def break, S2 Speed Up and a long CD S3 for AoE Dispell.' },
        { img: 'https://i.imgur.com/OjPkKIN.png',
          name: 'Celeste',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 6,
          abyss: 6,
          raid: 6.5,
          pve_average: 6.166666666666667,
          recommended_set: 'speed/crit ATK/crit',
          neck: 'critR',
          suggested_roles: 'AoE DPS',
          recommended_artifact: 'https://i.imgur.com/EqJsrv8.png',
          alternate_artifact: 'https://i.imgur.com/3vxEQrz.png',
          alternate_artifact2: 'https://i.imgur.com/jIFaJQV.png',
          note:
          '128 speed, easy spammale AoE attacks. Also a decent farmer if invested heavily. Otherworldy Machinery is only available in KR.' },
        { img: 'https://i.imgur.com/NnfsTZf.png',
          name: 'Doris',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8,
          abyss: 9,
          raid: 8.5,
          pve_average: 8.5,
          recommended_set: 'speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Healer\nBuffer',
          recommended_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact2: '',
          note:
          'She is top tier for abyss and hunt because of her Def buff + sustain on S2, and massive 1target heal on S3. However her abysmal base speed (86 which is the slowest of all units in game) makes speed set and boot almost a must for her.' },
        { img: 'https://i.imgur.com/CLf4BzV.png',
          name: 'Elson',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 5,
          abyss: 6.5,
          raid: 6,
          pve_average: 5.833333333333333,
          recommended_set: 'speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Buffer\nHealer',
          recommended_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'THE NERF hurts, can be used as a budget atk/def buffer and decent in some levels that not requiring buff coverage so much.' },
        { img: 'https://i.imgur.com/vDtfXgT.png',
          name: 'Gloomyrain',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6.5,
          abyss: 6,
          raid: 7,
          pve_average: 6.5,
          recommended_set: 'speed/crit ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nSupport',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/mJNvSR2.png',
          name: 'Gunther',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 4,
          abyss: 5,
          raid: 5,
          pve_average: 4.666666666666667,
          recommended_set: 'ATK/hit   ',
          neck: 'ATK',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact: 'https://i.imgur.com/3KKoV92.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/buSZqDF.png',
          name: 'Kikirat',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 4,
          abyss: 5.5,
          raid: 6.5,
          pve_average: 5.333333333333333,
          recommended_set: 'ALL DEF 2DEF/HP',
          neck: 'DEF',
          suggested_roles: 'Tank\nDPS\nDispel',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: undefined,
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/y5BR59i.png',
          name: 'Mirsa',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 4,
          abyss: 4,
          raid: 4,
          pve_average: 4,
          recommended_set: 'speed/hit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/PAlSNOv.png',
          alternate_artifact2: 'https://i.imgur.com/qgG8TFl.png',
          note: undefined },
        { img: 'https://i.imgur.com/M922PqX.png',
          name: 'Rikoris',
          star: 3,
          element: 'Light',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        { img: 'https://i.imgur.com/9LpaUj2.png',
          name: 'Aither',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 7.5,
          abyss: 6,
          raid: 6.5,
          pve_average: 6.666666666666667,
          recommended_set: 'ATK/HP speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Healer',
          recommended_artifact: 'https://i.imgur.com/eG33ZVm.png',
          alternate_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact2: '',
          note: 'Decent Ice healer.' },
        { img: 'https://i.imgur.com/rO9hzhi.png',
          name: 'Alexa',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 9.5,
          abyss: 7,
          raid: 6,
          pve_average: 7.5,
          recommended_set: 'critD/crit speed/crit',
          neck: 'critD',
          suggested_roles: 'ST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: '',
          note:
          '100% crit chance is needed. Her S1 has two ticks at 1.0 and 0.75, which can trigger Joker twice, making her top Wyvern 11 dpser. Her poison is also a bonus, but low base HP/DEF limits her usage elsewhere.' },
        { img: 'https://i.imgur.com/ldPk1Tw.png',
          name: 'Bask',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 8,
          abyss: 7.5,
          raid: 8,
          pve_average: 7.833333333333333,
          recommended_set: 'ALL HP speed/HP',
          neck: 'HP',
          suggested_roles: 'Tank\nImmunity\nDispel',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: 'https://i.imgur.com/6kPDlaB.png',
          note:
          'Great in a difficult fights with Immunity, Dispell and Attack Down.Can also be used as W11 tank.' },
        { img: 'https://i.imgur.com/ZXWRYqB.png',
          name: 'Enott',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 7,
          abyss: 5,
          raid: 5,
          pve_average: 5.666666666666667,
          recommended_set: 'speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nSelf-Buff\nDef Breaker',
          recommended_artifact: 'https://i.imgur.com/jlfXLQF.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/X3a5Fvo.png',
          name: 'Jena',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 4,
          raid: 4,
          pve_average: 4.666666666666667,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer',
          recommended_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/BxW3Ygd.png',
          name: 'Mistychain',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 9,
          abyss: 7,
          raid: 7,
          pve_average: 7.666666666666667,
          recommended_set: 'speed/crit lifesteal/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDebuffer\nSupport',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: '',
          note:
          'Wyvern Killer - AoE heal for the team while also doing competent single target damage. Her debuffs are ideal against bosses. Notice that she needs heavy Mola investments and is fragile.' },
        { img: 'https://i.imgur.com/9CslXCB.png',
          name: 'Montmorancy',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 7.5,
          abyss: 7.5,
          raid: 8,
          pve_average: 7.666666666666667,
          recommended_set: 'speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Immunity\nHealer',
          recommended_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact: 'https://i.imgur.com/eG33ZVm.png',
          alternate_artifact2: 'https://i.imgur.com/Oe2Xy9O.png',
          note: 'Budget Immunity provider and decent healer.' },
        { img: 'https://i.imgur.com/Dl5s3ZV.png',
          name: 'Rima',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 7,
          abyss: 6,
          raid: 7,
          pve_average: 6.666666666666667,
          recommended_set: 'speed/unity   speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'Support\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/vcX97Fa.png',
          alternate_artifact: 'The recommended artifact is essential for this character.',
          alternate_artifact2: '',
          note:
          'Rima is actually pretty strong if invested heavily and manual, her self cd reduction on S1, 117 base spd and dual-atk can make her skill spammable. High freq -3 cd on s3 is also great, kinda like a mini Iseria.' },
        { img: 'https://i.imgur.com/iJR2ggx.png',
          name: 'Taranor                 Royal Guard',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 7,
          abyss: 4,
          raid: 4,
          pve_average: 5,
          recommended_set: 'ALL HP',
          neck: 'HP',
          suggested_roles: 'Tank\nDispel',
          recommended_artifact: 'https://i.imgur.com/TiBmE8q.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note:
          'Ice tank with dmg reflection, can be used in W11 if you don\'t have other choices.' },
        { img: 'https://i.imgur.com/6yB6aES.png',
          name: 'Taranor                Guard',
          star: 3,
          element: 'Ice',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 9,
          abyss: 8,
          raid: 8,
          pve_average: 8.333333333333334,
          recommended_set: 'ALL unity\nspeed/hit',
          neck: 'critD',
          suggested_roles: 'Def Breaker\nCR Pusher\nDPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/3KKoV92.png',
          alternate_artifact2: '',
          note:
          'One of the best Ice def breakers, and a good CR pusher with Unity Set. He really shines in Wyvern hunt but high Mola investment is needed.' },
        { img: 'https://i.imgur.com/THuwUB7.png',
          name: 'Azalea',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6,
          abyss: 5.5,
          raid: 6,
          pve_average: 5.833333333333333,
          recommended_set: 'speed/HP   ',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer',
          recommended_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'Has high proc rate debuffs (speed debuff, heal ban, taunt) and has max hp based self heal on 1s. Budget heal ban choice.' },
        { img: 'https://i.imgur.com/KXDSSEA.png',
          name: 'Butcher Corps Inquisitor',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 6,
          abyss: 5,
          raid: 5,
          pve_average: 5.333333333333333,
          recommended_set: 'ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS\nDispel',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: '',
          note: 'Average Fire dps with buff removal.' },
        { img: 'https://i.imgur.com/IKy6m90.png',
          name: 'Carmainerose',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8.5,
          abyss: 7.5,
          raid: 8,
          pve_average: 8,
          recommended_set: 'speed/crit lifesteal/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDispell\nSelf-Buff',
          recommended_artifact: 'https://i.imgur.com/W7Pdbdk.png',
          alternate_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'Great utility kit + 1.5 multi S2/S3, with CR Decrese, Speed Down and Dispell, also three self-buffs(atk, def, speed) and lifesteal on S1. Used to be a decent all rounder but HP/DEF limits her now.' },
        { img: 'https://i.imgur.com/41Wuq9B.png',
          name: 'Carrot',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 6,
          abyss: 5,
          raid: 6,
          pve_average: 5.666666666666667,
          recommended_set: 'ATK/HP ATK/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/I13Wu2h.png',
          name: 'Hazel',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        { img: 'https://i.imgur.com/YgFzkbP.png',
          name: 'Judith',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 6,
          abyss: 5.5,
          raid: 5,
          pve_average: 5.5,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'CR Pusher\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note: 'Mostly used in PvP as opener.' },
        { img: 'https://i.imgur.com/JZpTZLb.png',
          name: 'Mascot Hazel',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 10,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.833333333333334,
          recommended_set: 'speed/hit speed/HP',
          neck: 'HP',
          suggested_roles: 'Buffer\nDebuffer\nHealer',
          recommended_artifact: 'https://i.imgur.com/2sCiR86.png',
          alternate_artifact: 'https://i.imgur.com/wIOvrGD.png',
          alternate_artifact2: '',
          note:
          'She\'s the ideal Golem 11 supporter/tank and provides great support to Fire heroes.' },
        { img: 'https://i.imgur.com/LIdczqI.png',
          name: 'Nemunas',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 7,
          abyss: 7.5,
          raid: 5,
          pve_average: 6.5,
          recommended_set: 'critD/crit',
          neck: 'critD',
          suggested_roles: 'ST DPS\nCleanse\nSupport',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Can be used for her HP% dmg and cleanse.' },
        { img: 'https://i.imgur.com/atU06bA.png',
          name: 'Ras',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 5,
          abyss: 6.5,
          raid: 6,
          pve_average: 5.833333333333333,
          recommended_set: 'speed/HP',
          neck: 'critR\nHP',
          suggested_roles: 'DPS\nSupport',
          recommended_artifact: 'https://i.imgur.com/ErTlk2z.png',
          alternate_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact2: 'https://i.imgur.com/FvNdP5K.png',
          note:
          'Sometime used as a dual atker, overshadowed by Kitty and Tamarinne now.' },
        { img: 'https://i.imgur.com/fGILtB8.png',
          name: 'Tieria',
          star: 3,
          element: 'Fire',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6.5,
          abyss: 6,
          raid: 6,
          pve_average: 6.166666666666667,
          recommended_set: 'speed/crit critD/crit',
          neck: 'critD',
          suggested_roles: 'CR Pusher\nST DPS\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'THE NERF destroyed her mostly, can be used as a OK level CR pusher with meh speed and HP % dmg, but rarely chosen with better choices being there.' },
        { img: 'https://i.imgur.com/u5R9ozm.png',
          name: 'Adlay',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 4,
          abyss: 5,
          raid: 5,
          pve_average: 4.666666666666667,
          recommended_set: 'speed/hit ',
          neck: 'critR\ncritD',
          suggested_roles: 'Support ',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: undefined,
          note: undefined },
        { img: 'https://i.imgur.com/T8nnwZi.png',
          name: 'Falconer Kluri',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 9.5,
          abyss: 9.5,
          raid: 9.5,
          pve_average: 9.5,
          recommended_set: 'speed/hit speed/unity',
          neck: 'DEF\nHP',
          suggested_roles: 'Def Breaker\nTank\nSupport',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: 'https://i.imgur.com/6kPDlaB.png',
          note:
          'Great team utility, covers several roles. Top def break/dispell, part healer, part CR support, full time tank. Also is one of the fastest tanks with extra, helping to build up soul faster. 100% Taunt can cheese hard Abyss levels like 73.' },
        { img: 'https://i.imgur.com/Y6kvtL4.png',
          name: 'Helga',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6.5,
          abyss: 7,
          raid: 5,
          pve_average: 6.166666666666667,
          recommended_set: 'speed/hit',
          neck: 'critR',
          suggested_roles: 'Def Breaker\nBuffer',
          recommended_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'She\'s a budget atk buffer alternative besides Hazel for those have no Diene, also with def break on her S1.\n' },
        { img: 'https://i.imgur.com/YUWgQGz.png',
          name: 'Jecht',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 9,
          abyss: 6.5,
          raid: 7.5,
          pve_average: 7.666666666666667,
          recommended_set: 'speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Cleanse\nHealer\nBuffer',
          recommended_artifact: 'https://i.imgur.com/sEynPik.png',
          alternate_artifact: '',
          alternate_artifact2: '',
          note:
          'Wonderous Potion vial for passive, high speed in healer and a HoT on his S3, really shines in Banshee 11.' },
        { img: 'https://i.imgur.com/Tw9eUfC.png',
          name: 'Kiris',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 7.5,
          abyss: 10,
          raid: 5,
          pve_average: 7.5,
          recommended_set: 'speed/hit   speed/HP',
          neck: 'DEF\nHP',
          suggested_roles: 'Debuffer\nST DPS',
          recommended_artifact: 'https://i.imgur.com/6nIJ3yJ.png',
          alternate_artifact: 'https://i.imgur.com/bmewePw.png',
          alternate_artifact2: '',
          note:
          'One of the most chosen characters for Abyss, can cheese many of hard Abyss levels incl.80-90. A great Golem killer in early game.' },
        { img: 'https://i.imgur.com/b8HLTDI.png',
          name: 'Kluri',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        { img: 'https://i.imgur.com/GjY1hem.png',
          name: 'Mucacha',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 6,
          abyss: 5,
          raid: 6.5,
          pve_average: 5.833333333333333,
          recommended_set: 'speed/hit speed/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nST DPS\nSelf-Buff',
          recommended_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'With investment, Mucacha can be an option for a DEF Breaker (speed/hit) or DPS (speed/crit) while bringing a +8 Speed buff to your party at SSS.  ' },
        { img: 'https://i.imgur.com/3hdPR7Z.png',
          name: 'Pearlhorizon',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 4,
          abyss: 5,
          raid: 5,
          pve_average: 4.666666666666667,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer',
          recommended_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact2: '',
          note:
          'An average damage dealer with some AoE and several debuffs. Her S3 has a 100% chance stun for 1 turn, which also does 20% max HP damage to one sleeping target, but since most bosses don\'t sleep would be difficult to execute.' },
        {
          img:
          'https://cdn.discordapp.com/attachments/517186653820026910/542850837894922243/roozidr.png',
          name: 'Righteous Thief Roozid',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 7.5,
          abyss: 6,
          raid: 6,
          pve_average: 6.5,
          recommended_set: 'speed/hit ',
          neck: 'critR\ncritD',
          suggested_roles: 'CR Pusher\nBuffer\nDebuffer',
          recommended_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact: 'https://i.imgur.com/n9ptTXy.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note: undefined },
        { img: 'https://i.imgur.com/sC8HMao.png',
          name: 'Roozid',
          star: 3,
          element: 'Earth',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        {
          img: 'https://cdn.discordapp.com/attachments/517186653820026910/529027079778467850/axegodd.png',
          name: 'Chaos Sect Axe',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 8.5,
          raid: 9,
          pve_average: 8.666666666666666,
          recommended_set: 'lifesteal/crit speed/HP',
          neck: 'critR\nATK',
          suggested_roles: 'Def Breaker\nDPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/hAWHylj.png',
          alternate_artifact2: 'https://i.imgur.com/NA8VplW.png',
          note: 'Tanky def breaker with great aoe and dps.' },
        { img: 'https://i.imgur.com/aWoWDG9.png',
          name: 'Church of Ilryos Axe',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        { img: 'https://i.imgur.com/UbEt4G9.png',
          name: 'Commander Lorina',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: 8.5,
          abyss: 9.5,
          raid: 9.5,
          pve_average: 9.166666666666666,
          recommended_set: 'lifesteal/crit     critD/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'ST DPS',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/jlfXLQF.png',
          alternate_artifact2: 'https://i.imgur.com/NA8VplW.png',
          note:
          'Top general damage dealer. She has a passive modifier of 1.75, making her S1 300%+ per hit, as high as many chars\' S3. Her burst may be bit lacking among tops. Great morale ability (easily 40+) makes her a top choice for Raid.' },
        {
          img: 'https://i.imgur.com/qTkkFOU.png',
          name: 'Hurado',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 4,
          abyss: 4,
          raid: 4,
          pve_average: 4,
          recommended_set: 'speed/hit ',
          neck: 'DEF\nHP',
          suggested_roles: 'Support',
          recommended_artifact: 'https://i.imgur.com/eaZzKvc.png',
          alternate_artifact: 'https://i.imgur.com/1IAXhSi.png',
          alternate_artifact2: '',
          note: 'The kit is more focused on PvP.\n' },
        { img: 'https://i.imgur.com/2j9GyDH.png", 1)',
          name: 'Lorina',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/a34GyyB.png',
          hunt: '',
          abyss: '',
          raid: '',
          pve_average: 0,
          recommended_set: '',
          neck: '',
          suggested_roles: '',
          recommended_artifact: '',
          alternate_artifact: '',
          alternate_artifact2: '',
          note: 'Specialty Change.' },
        { img: 'https://i.imgur.com/K0hDoKk.png',
          name: 'Otillie',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/hGAL2QJ.png',
          hunt: 8,
          abyss: 6,
          raid: 6.5,
          pve_average: 6.833333333333333,
          recommended_set: 'speed/crit    ',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer\nSupport',
          recommended_artifact: 'https://i.imgur.com/PjdYo5S.png',
          alternate_artifact: 'https://i.imgur.com/1IAXhSi.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'Reduces AoE damage you take + heal ban + buff ban. A specific char made for Golem.' },
        { img: 'https://i.imgur.com/BEdP4q0.png',
          name: 'Pyllis',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/3OCQgMB.png',
          hunt: 8,
          abyss: 8,
          raid: 8,
          pve_average: 8,
          recommended_set: '2DEF/HP 2DEF/hit',
          neck: 'DEF',
          suggested_roles: 'Tank\nBuffer',
          recommended_artifact: 'https://i.imgur.com/lIy8T6J.png',
          alternate_artifact: 'https://i.imgur.com/FvNdP5K.png',
          alternate_artifact2: 'https://i.imgur.com/6kPDlaB.png',
          note:
          'Top PvE defender, with kinda exessive defensing capabilty in current meta. Her dmg from DEF scaling is pretty great, making stack on DEF a good choice.\n' },
        { img: 'https://i.imgur.com/vcfivZq.png',
          name: 'Requiemroar',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/TsuJvXE.png',
          hunt: 8.5,
          abyss: 8,
          raid: 8.5,
          pve_average: 8.333333333333334,
          recommended_set: 'speed/hit    ',
          neck: 'critR\ncritD',
          suggested_roles: 'Def Breaker\nSupport',
          recommended_artifact: 'https://i.imgur.com/4jLh7K3.png',
          alternate_artifact: 'https://i.imgur.com/Oe2Xy9O.png',
          alternate_artifact2: 'https://i.imgur.com/sEynPik.png',
          note:
          'Gives teamwide lifesteal and CR, while employing various debuffs esp Def Break. Note: No matter what sets you give her, she needs tanky substats/mainstats since she is very squishy.' },
        { img: 'https://i.imgur.com/VqdXpMX.png',
          name: 'Sven',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/YZa7qSv.png',
          hunt: 5,
          abyss: 6,
          raid: 5,
          pve_average: 5.333333333333333,
          recommended_set: 'lifesteal/crit',
          neck: 'critR\ncritD',
          suggested_roles: 'DPS\nSelf-Buff',
          recommended_artifact: 'https://i.imgur.com/OZC1SjY.png',
          alternate_artifact: 'https://i.imgur.com/qgG8TFl.png',
          alternate_artifact2: 'https://i.imgur.com/vI1I5KU.png',
          note: undefined },
        { img: 'https://i.imgur.com/jhheIa4.png',
          name: 'Wanda',
          star: 3,
          element: 'Dark',
          class: 'https://i.imgur.com/4UWNMER.png',
          hunt: 6,
          abyss: 5,
          raid: 5.5,
          pve_average: 5.5,
          recommended_set: 'speed/hit',
          neck: 'critR\ncritD',
          suggested_roles: 'Debuffer',
          recommended_artifact: 'https://i.imgur.com/vcX97Fa.png',
          alternate_artifact: 'https://i.imgur.com/VeN5nfe.png',
          alternate_artifact2: 'https://i.imgur.com/OZC1SjY.png',
          note:
          'Can be used at Wyvern 10 as a stable debuff provider and dual atker.' }
      ]
    }
  }
}
</script>
